Repository uPortal-Project/uPortal-web-components, pull requests merged in 2018-10, with the labels that each got.

#118 fix(waffle-menu): web component standard version 1 support
  @uportal/waffle-menu/package-lock.json
  @uportal/waffle-menu/package.json
  @uportal/waffle-menu/public/index.html
  @uportal/waffle-menu/src/index.js
Labels: bug, help wanted

#142 feat(esco-content-menu): slot grid header
  @uportal/esco-content-menu/src/components/ContentGrid.vue
Labels: enhancement, semver minor

#147 build: bundle slick theme with package
  @uportal/content-carousel/README.md
  @uportal/content-carousel/package.json
  docs/en/components/content-carousel/README.md
  docs/en/components/content-carousel/demo.html
Labels: bug, semver patch

#143 Reviewing isSmall to different size
  @uportal/esco-content-menu/src/App.vue
  @uportal/esco-content-menu/src/components/ActionFavorites.vue
  @uportal/esco-content-menu/src/components/ContentFavorites.vue
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentMenu.vue
  @uportal/esco-content-menu/src/components/ContentUser.vue
  @uportal/esco-content-menu/src/components/PortletCard.vue
  @uportal/esco-content-menu/src/services/sizeTools.js
  @uportal/esco-content-menu/src/styles/vars.scss
Labels: enhancement, hacktoberfest, semver minor
