Repository uPortal-Project/uPortal-web-components, pull requests merged in 2019-02, with the labels that each got.

#251 Updated the docs for creating web components with Vue
  docs/en/ADD_COMPONENT_TO_UPORTAL.md
  docs/en/developer/create-web-component/VUE.md
Labels: enhancement, good first issue, semver patch

#255 docs(vue.md): provide the french translation of vue.js guide + fix in title hierarchy in the english doc
  docs/en/developer/create-web-component/VUE.md
  docs/fr/developer/create-web-component/VUE.md
Labels: enhancement, semver patch

#260 ci: test on lts and stable node, and on osx and windows
  .travis.yml
Labels: enhancement, semver patch

#259 feat: refactored the component to Vue
  @uportal/waffle-menu/.eslintrc.json
  @uportal/waffle-menu/babel.config.js
  @uportal/waffle-menu/package-lock.json
  @uportal/waffle-menu/package.json
  @uportal/waffle-menu/public/api/menu.json
  @uportal/waffle-menu/public/index.html
  @uportal/waffle-menu/public/portletRegistry.json
  @uportal/waffle-menu/src/App.vue
  @uportal/waffle-menu/src/WaffleMenu.js
  @uportal/waffle-menu/src/components/WaffleMenu.vue
  @uportal/waffle-menu/src/index.js
  @uportal/waffle-menu/src/main.js
Labels: enhancement, semver patch

#258 fix: make axios resove promises even for non-200 status
  @uportal/api-template-vue/src/components/ApiTemplateVue.vue
  package-lock.json
Labels: bug, semver patch

#262 cleaned up VUE.md and added quick build instructions
  docs/en/developer/create-web-component/VUE.md
Labels: enhancement, semver patch
