Repository uPortal-Project/uPortal-web-components, pull requests merged in 2019-03, with the labels that each got.

#279 Feat/user profile slots
  @uportal/user-profile-menu/.gitignore
  @uportal/user-profile-menu/.nvmrc
  @uportal/user-profile-menu/README.md
  @uportal/user-profile-menu/babel.config.js
  @uportal/user-profile-menu/package-lock.json
  @uportal/user-profile-menu/package.json
  @uportal/user-profile-menu/public/favicon.ico
  @uportal/user-profile-menu/public/index.html
  @uportal/user-profile-menu/src/App.vue
  @uportal/user-profile-menu/src/assets/logo.png
  @uportal/user-profile-menu/src/components/ProfileMenu.vue
  @uportal/user-profile-menu/src/main.js
  @uportal/user-profile-menu/vue.config.js
  README.md
  settings.gradle
Labels: enhancement, semver minor

#281 docs: replace symlink to provide docs on npm site
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/public/adminPortlets.json
  @uportal/esco-content-menu/public/layout.json
  @uportal/esco-content-menu/public/orginfo.json
  @uportal/esco-content-menu/public/portletRegistry.json
  @uportal/esco-content-menu/public/userinfo.json
  @uportal/eyebrow-user-info/README.md
Labels: enhancement

#285 fix: use wrong param AlternativeMaximizedLink + improvements
  @uportal/waffle-menu/README.md
  @uportal/waffle-menu/src/components/WaffleMenu.vue
  docs/en/components/waffle-menu/README.md
Labels: bug, enhancement

#295 fix (esco-content-menu): Fix recursion on swipper
  @uportal/esco-content-menu/public/portletRegistry.json
  @uportal/esco-content-menu/src/components/ContentFavorites.vue
  docs/en/components/esco-content-menu/portletRegistry.json
Labels: bug
