Repository uPortal-Project/uPortal-web-components, pull requests merged in 2019-05, with the labels that each got.

#303 providing some improvements on esco-content-menu
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/public/index.html
  @uportal/esco-content-menu/src/App.vue
  @uportal/esco-content-menu/src/components/ContentFavorites.vue
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentMenu.vue
  @uportal/esco-content-menu/src/components/ContentUser.vue
  @uportal/esco-content-menu/src/components/HamburgerMenu.vue
  @uportal/esco-content-menu/src/i18n.js
  @uportal/esco-content-menu/src/locales/en-US.json
  @uportal/esco-content-menu/src/locales/fr-FR.json
  docs/en/components/esco-content-menu/README.md
Labels: enhancement

#334 chore: add nvmrc
  .nvmrc
Labels: enhancement, semver patch

#335 docs: update demo page dependencies
  docs/en/components/content-carousel/demo.html
  docs/en/components/dashboard-carousel/demo.html
  docs/en/components/esco-content-menu/demo.html
  docs/en/components/waffle-menu/demo.html
Labels: bug, semver patch
