Repository uPortal-Project/uPortal-web-components, pull requests merged in 2019-01, with the labels that each got.

#193 feat: allow each Web Component to install a -SNAPSHOT to Maven local
  .gitignore
  @uportal/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement

#195 feat(esco-content-menu): add hide-title attribute option
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/src/components/ContentGrid.vue
Labels: enhancement, semver patch

#197 fix(esco-content-grid): remove small(er) background color
  @uportal/esco-content-menu/src/components/ContentGrid.vue
Labels: bug, semver patch

#203 chore: update package lock files to pin webpack dev server to 3.1.11+
  @uportal/content-carousel/package-lock.json
  @uportal/content-carousel/package.json
  @uportal/esco-content-menu/package-lock.json
  @uportal/esco-content-menu/package.json
  @uportal/eyebrow-user-info/package-lock.json
  @uportal/eyebrow-user-info/package.json
  @uportal/open-id-connect/package-lock.json
  @uportal/portlet-registry-to-array/package-lock.json
  @uportal/waffle-menu/package-lock.json
  package-lock.json
Labels: semver patch

#202 docs: add steps for legacy browser support
  docs/en/developer/create-web-component/VUE.md
Labels: enhancement, semver patch

#201 feat(esco-content-grid): add external category grid filter
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentGridFilter.vue
Labels: enhancement, semver minor

#200 Feat/dashboard carousel
  @uportal/dashboard-carousel/README.md
  @uportal/dashboard-carousel/babel.config.js
  @uportal/dashboard-carousel/package-lock.json
  @uportal/dashboard-carousel/package.json
  @uportal/dashboard-carousel/public/favicon.ico
  @uportal/dashboard-carousel/public/index.html
  @uportal/dashboard-carousel/public/layout.json
  @uportal/dashboard-carousel/serve.json
  @uportal/dashboard-carousel/src/App.vue
  @uportal/dashboard-carousel/src/assets/logo.png
  @uportal/dashboard-carousel/src/components/DashboardCarousel.vue
  @uportal/dashboard-carousel/src/components/PortletRenderer.vue
  @uportal/dashboard-carousel/src/main.js
  README.md
  docs/en/developer/SNAPSHOT.md
  settings.gradle
Labels: enhancement, semver minor

#207 docs(dashboard-carousel): add npm, maven, and ci badges to readme
  @uportal/dashboard-carousel/README.md
Labels: enhancement, semver patch

#205 fix(content-grid-filter): fix event name and styling
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentGridFilter.vue
Labels: bug, semver patch

#210 fix: sample data so local node setup works
  @uportal/dashboard-carousel/public/layout.json
Labels: bug, semver patch

#211 build(dashboard-carousel): declare source and main files in package
  @uportal/dashboard-carousel/package.json
Labels: enhancement, semver patch

#212 fix(dashboard-carousel): debug mode
  @uportal/dashboard-carousel/src/components/DashboardCarousel.vue
  @uportal/dashboard-carousel/src/components/PortletRenderer.vue
Labels: bug, semver patch

#213 refactor(dashboard-carousel): avoid confusing `layout.layout` in code
  @uportal/dashboard-carousel/src/components/DashboardCarousel.vue
Labels: semver patch

#214 feat(dashboard-carousel): configurable selected region
  @uportal/dashboard-carousel/README.md
  @uportal/dashboard-carousel/src/components/DashboardCarousel.vue
Labels: enhancement, semver minor

#215 docs: add dashboard carousel to top level readme
  README.md
Labels: enhancement, semver patch

#208 docs: enhance instructions for creating a component with Vue
  docs/en/developer/create-web-component/VUE.md
Labels: enhancement, semver patch

#216 docs: include example html for portlet
  @uportal/dashboard-carousel/public/example-portlet.html
  @uportal/dashboard-carousel/public/layout.json
Labels: enhancement, semver patch

#224 refactor(esco-content-menu): on API Urls for demo/standalone use
  @uportal/esco-content-menu/.env
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/public/adminPortlets.json
  @uportal/esco-content-menu/public/browseable.json
  @uportal/esco-content-menu/public/layout.json
  @uportal/esco-content-menu/public/orginfo.json
  @uportal/esco-content-menu/public/portletRegistry.json
  @uportal/esco-content-menu/public/userinfo.json
  @uportal/esco-content-menu/src/App.vue
  @uportal/esco-content-menu/src/components/ActionFavorites.vue
  @uportal/esco-content-menu/src/components/ContentFavorites.vue
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentMenu.vue
  @uportal/esco-content-menu/src/components/HamburgerMenu.vue
  @uportal/esco-content-menu/src/components/PortletCard.vue
  @uportal/esco-content-menu/src/services/fetchFavorites.js
  @uportal/esco-content-menu/src/services/fetchPortlets.js
  @uportal/esco-content-menu/src/services/fetchUserInfoAndOrgs.js
  @uportal/esco-content-menu/src/services/managePortletUrl.js
  @uportal/esco-content-menu/src/services/portlet-registry-to-array.js
  @uportal/eyebrow-user-info/README.md
  docs/en/README.md
  docs/en/components/README.md
  docs/en/components/esco-content-menu/README.md
  docs/en/components/esco-content-menu/adminPortlets.json
  docs/en/components/esco-content-menu/demo.html
  docs/en/components/esco-content-menu/layout.json
  docs/en/components/esco-content-menu/orginfo.json
  docs/en/components/esco-content-menu/portletRegistry.json
  docs/en/components/esco-content-menu/userinfo.json
  docs/en/components/eyebrow-user-info/README.md
Labels: enhancement, help wanted

#192 refactor(esco-content-menu): use the portletRegistry API
  @uportal/esco-content-menu/.env
  @uportal/esco-content-menu/README.md
  @uportal/esco-content-menu/public/browseable.json
  @uportal/esco-content-menu/public/portletRegistry.json
  @uportal/esco-content-menu/src/components/ActionFavorites.vue
  @uportal/esco-content-menu/src/components/ContentFavorites.vue
  @uportal/esco-content-menu/src/components/ContentGrid.vue
  @uportal/esco-content-menu/src/components/ContentMenu.vue
  @uportal/esco-content-menu/src/components/PortletCard.vue
  @uportal/esco-content-menu/src/services/fetchPortlets.js
  @uportal/esco-content-menu/src/services/managePortletUrl.js
  @uportal/esco-content-menu/src/services/portlet-registry-to-array.js
Labels: enhancement, help wanted

#225 Provide a new component that invokes an API (w/ OIDC token) and renders a Vue template
  @uportal/api-template-vue/README.md
  @uportal/api-template-vue/babel.config.js
  @uportal/api-template-vue/package-lock.json
  @uportal/api-template-vue/package.json
  @uportal/api-template-vue/public/example.json
  @uportal/api-template-vue/public/favicon.ico
  @uportal/api-template-vue/public/index.html
  @uportal/api-template-vue/src/App.vue
  @uportal/api-template-vue/src/assets/logo.png
  @uportal/api-template-vue/src/components/ApiTemplateVue.vue
  @uportal/api-template-vue/src/main.js
  @uportal/api-template-vue/vue.config.js
  README.md
  package-lock.json
  settings.gradle
Labels: enhancement, semver minor, work in progress

#233 docs: bump core-js-bundle to 3.0.0-beta.8 like uPortal#1499
  docs/en/components/content-carousel/demo.html
  docs/en/components/dashboard-carousel/demo.html
  docs/en/components/esco-content-menu/demo.html
  docs/en/components/waffle-menu/demo.html
Labels: enhancement, semver patch
